  vars:
    falcon_client_id: xxxxxxxxxxxxxxxxxxxxx
    falcon_client_secret: xxxxxxxxxxxxxxxxxxxxx
  roles:
  - role: crowdstrike.falcon.falcon_install
    vars:
      falcon_sensor_version_decrement: 2
  - role: crowdstrike.falcon.falcon_configure
    vars:
      # falcon_cid is autodetected using falcon_client_id|secret vars
      falcon_tags: 'falcon,example,tags'
