---
- hosts: 54.163.16.195
  remote_user: core
  tasks:
  - name: Ensure podman socket is running
    ansible.builtin.systemd:
      name: podman.socket
      state: started
      enabled: true
      scope: user
  
  - name: ensure directory exists
    file:
      path: "{{ ansible_env.HOME }}/.fetchit"
      state: directory
      mode: '0755'

  - name: Get file from URL
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/sallyom/fetchit/main/examples/config-reload.yaml
      dest: "{{ ansible_env.HOME }}/.fetchit/config.yaml"
    register: fetchit_config

  - name: Create user systemd directory if it does not exist
    ansible.builtin.file:
      path: "{{ ansible_env.HOME }}/.config/systemd/user"
      state: directory
      mode: '0755'

  - name: Record the fetchit containers status
    containers.podman.podman_container_info:
      name: fetchit
    register: fetchit_container_info
    ignore_errors: true 

  - name: Get file from URL
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/sallyom/fetchit/main/systemd/fetchit-user.service
      dest: "{{ ansible_env.HOME }}/.config/systemd/user/fetchit.service"

  - name: Ensure fetchit service is running
    ansible.builtin.systemd:
      name: fetchit
      state: started
      enabled: true
      scope: user
    when: fetchit_config is changed or fetchit_container_info.stderr != ""
