---
- name: Run osbuild_builder role
  become: true
  gather_facts: true
  hosts: all
  vars:
    builder_wait_compose_timeout: 2400
    builder_request_timeout: 600
  tasks:
    - name: Run the role
      ansible.builtin.import_role:
        name: infra.osbuild.builder
